### ISSUE TITLE
Feature Request - Allow copying or sharing info

### ISSUE THREAD

**Issue by laduko** [ErikKalkoken/evebuddy#14]
It would be nice to allow copying/sharing parts of the info in app (Mails, Skill Queue..etc) rather than taking screenshots.

Just a minor thing and not really important compared to other features! :)

**Comment by ErikKalkoken** [comment]
I implemented button to copy mails and notifications clipboard. If you get the chance, please let me know how that works for you.

**Comment by laduko** [comment]
> I implemented button to copy mails and notifications clipboard. If you get the chance, please let me know how that works for you.

Works like a charm, thank you!
