### ISSUE TITLE
Extremely slow scrolling

### ISSUE THREAD

**Issue by ppfeufer** [ErikKalkoken/evebuddy#22]
AppImage v0.6.2

https://github.com/user-attachments/assets/e1ba7749-26bf-4ad7-b19f-3d09a53e15b0

**Comment by ppfeufer** [comment]
Same with v0.6.3

**Comment by ppfeufer** [comment]
Desktop:
KDE Plasma 6 / Wayland session

**Comment by ErikKalkoken** [comment]
Thanks for posting this issue and the video. I will look into it.

**Comment by ErikKalkoken** [comment]
When you get the chance, please let me know if the fix worked for you.

**Comment by ppfeufer** [comment]
Yep, working!
