### ISSUE TITLE
macOS: resizing window causes a crash

### ISSUE THREAD

**Issue by jcorwin137** [ErikKalkoken/evebuddy#29]
Resizing a window causes the application to crash. It is most prevalent on the Characters:Asset window

EVE Buddy 0.7.0 - Intel
macOS 12.7.6
Apple Silicon

**Comment by ErikKalkoken** [comment]
This is a known issue when trying to use the intel build on Apple Silicon.

Can you please try to use the arm build, which is specifically made for Apple Silicon. You probably need to use the workaround as documented in the README to get it working. 

Related issues with the Fyne GUI toolkit for reference:
- [Panic on window resize on macOS](https://github.com/fyne-io/fyne/issues/4708)
- [Support Apple intel apps on M1/2 (using Rosetta)](https://github.com/fyne-io/fyne/issues/3971)

**Comment by jcorwin137** [comment]
The ARM version with workaround does work. Thank you.
