### ISSUE TITLE
Feature Request - PI Extraction Tracking

### ISSUE THREAD

**Issue by Tanthalas-Solostaran** [ErikKalkoken/evebuddy#34]
Hey Erik,

It would be incredible if PI was able to be tracked using this desktop app. Whether that's actively tracking the timer on an extraction via ESI, or if it can somehow see how long an extraction is set for and set some kind of internal clock/alarm. 

I understand that it's unlikely there are any standard eve ESI notifications for PI, but have seen something like this done via the browser before. Not sure how that person managed it, but moving it from a browser based function into a desktop application that lives in the background would be awesome.

**Comment by ErikKalkoken** [comment]
I took a quick look at ESI and it seams like it would not be possible to calculate any kind of timers from the provided data.

Can you maybe provide me more information about the website you mentions, so I can maybe find out more about how that works?

I still plan to add the list of owned colonies though, which is what you can get from the ESI.

See also #5

**Comment by Tanthalas-Solostaran** [comment]
Hey Erik,

The website is https://planetsin.space/

Excellent!

**Comment by ErikKalkoken** [comment]
I have implemented your feature request. Would very much appreciate your feedback if you get the change to check it out.
