### ISSUE TITLE
PI Overview

### ISSUE THREAD

**Issue by bubis7** [ErikKalkoken/evebuddy#5]
Would be cool to see PI data at a glance. Under "Characters" a new Tab that would just list all character PI planets, and when extraction ends on each planet if there is any extraction (Non factory planets).
With the intent of keeping Eve Buddy as a background app, then notifications of these extractions times coming to end would also be nice

**Comment by ErikKalkoken** [comment]
Thank you for your feature request. I am currently focusing on fixing bugs and improving existing features. But I think it is a good idea and I'd be happy to consider for a future release.

**Comment by ErikKalkoken** [comment]
I have implemented your feature request. Would very much appreciate your feedback if you get the change to check it out.
