### ISSUE TITLE
App crash on start

### ISSUE THREAD

**Issue by thegilm** [ErikKalkoken/evebuddy#7]
Hello again,

current version 0.3.0 crashes on Windows 10 22H2 on start of the app. Might have again something to do with freshly added characters, I'm not sure.
Crash report attached
[crash.txt](https://github.com/user-attachments/files/17338878/crash.txt)

Cheers!

**Comment by ErikKalkoken** [comment]
Thank you very much for continue to test the app and report issues. That is super helpful.

I will look into this.

BTW. You are also very welcome to join our Discord server, if you like. We have a dedicated support channel for Eve Buddy there. 
https://discord.gg/tVSCQEVJnJ

**Comment by ErikKalkoken** [comment]
Bug confirmed. This was likely caused by a structure, which could not be resolved. Fix comes with new version 0.3.1.
If you have the chance, please let me know if that fix works for you.

**Comment by thegilm** [comment]
0.3.1 works fine for me, thanks for the speedy fix!
